### PR TITLE
Move the installer to be a default

### PR DESCRIPTION
**Pull request by sgenoud**
It allows it to be overridable by playbooks.

### CODE REVIEW

**Comment by uchida** [comment]
@sgenoud thank you to send this pull request.

However, I'm hesitating to merge because setting `miniconda_installer` and `miniconda_python`,`miniconda_version` may introduce confusing to users.

What is the use-case for this pull request?

**Comment by sgenoud** [comment]
In my case I had the interpretation of the facts break (for a reason I did not dig too much into - I guess this is related to the fact that I do not gather facts). In that case it is the easiest to replace the full installer name than to fiddle with the configuration.

If you wanted to make it more explicit we could have two different ways to expose the installer name, either directly or using facts.

**Comment by uchida** [comment]
Thank you for letting me know your use-case.

Sure, the role currently requires to `gather_facts: True`, this is a compromise because `ansible_os_family` may requires `gather_facts: True`.

Giving a fallback variable for the case `gather_facts: False` seems acceptable.
However, giving following variables to role by hands without gathering facts may work with your use-case.

- `ansible_system`: `Linux` or `Darwin`
- `ansible_architecture`: one of `x86_64` or `i386`, `armv7l`, `ppc64le`

Could you try it?

**Comment by uchida** [comment]
Manually setting `ansible_os_family`, `ansible_system`, `ansible_architecture` will work for this case.
I added test case for `gather_facts: no` and notes in README in #8.
I will close this pull request.

**Pull request closed without merging**
